Models/Permissao.cs
using System;
using System.Collections.Generic;

namespace GerenciadorDeUsuarios.Models
{
    public class Permissao
    {
        public Guid PermissaoId { get; set; }        
        public string Nome { get; set; }
        public IList<PermissoesUsuario> PermissoesUsuario { get; set; }

    }
}

Models/Usuario.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace GerenciadorDeUsuarios.Models
{
    public class Usuario
    {
        public Guid UsuarioId { get; set; }

        [Required(ErrorMessage = "Esse campo não pode estar vazio!")]
        [StringLength(100, ErrorMessage = "Tamanho maximo de 100 caracteres" )]
        public string Nome { get; set; }
        
        [Required(ErrorMessage = "Esse campo não pode estar vazio!")]
        [StringLength(255, ErrorMessage = "Tamanho maximo de 255 caracteres!")]
        [EmailAddress]
        public string Email { get; set; }
        
        [Required(ErrorMessage = "Esse campo não pode estar vazio!")]
        [StringLength(10, MinimumLength = 3, ErrorMessage="Quantidade de caracteres invalida")]
        public string Senha { get; set; }
        public IList<PermissoesUsuario> PermissoesUsuario {get;set;} = new List<PermissoesUsuario>();

    }
}

Models/UsuarioViewModel.cs
using System.Collections.Generic;

namespace GerenciadorDeUsuarios.Models
{
    public class UsuarioViewModel
    {
        public IList<Usuario> Usuarios { get; set; }
        public int QuantPaginas { get; set; }
        
        public UsuarioViewModel(IList<Usuario> usuarios, int quantidadeDePaginas)
        {
            this.Usuarios = usuarios;
            this.QuantPaginas = quantidadeDePaginas;
        }
        public UsuarioViewModel()
        {
            
        }
    }
}

Controllers/PermissaoController.cs
using System;
using System.Threading.Tasks;
using GerenciadorDeUsuarios.Models;
using GerenciadorDeUsuarios.Repositorios;
using Microsoft.AspNetCore.Mvc;

namespace GerenciadorDeUsuarios.Controllers
{
    public class PermissaoController : Controller
    {
        public IRepositorioBase<Permissao> Permissoes { get; }
        public PermissaoController(IRepositorioBase<Permissao> permissoes)
        {
            this.Permissoes = permissoes;

        }
        public async Task<IActionResult> Todos()
        {
            var permissoes = await Permissoes.GetAll();
            return View(permissoes);
        }


        public IActionResult Novo()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Novo([FromForm]Permissao Permissao)
        {
            if(ModelState.IsValid)
            {
              await Permissoes.Save(Permissao);
              return RedirectToAction("Todos");  
            }           
            return View();                 
        }


        public async Task<IActionResult> Editar(Guid id)
        {
            var permissao = await Permissoes.GetById(id);
            return View(permissao);
        }

        [HttpPost]
        [AutoValidateAntiforgeryToken]
        public async Task<IActionResult> Editar([FromForm]Permissao Permissao, Guid id)
        {
            Permissao.PermissaoId = id;
            await Permissoes.Update(Permissao);
            return RedirectToAction("Todos");
        }

        public async Task<IActionResult> Deletar(Guid id)
        {
            var permissao = await Permissoes.GetById(id);
            return View(permissao);
        }

        [HttpPost, ActionName("Deletar")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> ConfirmacaoDeletar(Guid id)
        {
            
            await Permissoes.Delete(id);
            return RedirectToAction("Todos");
        }

      
    }
}

Controllers/UsuarioController.cs
using System;
using System.Linq;
using System.Threading.Tasks;
using GerenciadorDeUsuarios.Models;
using GerenciadorDeUsuarios.Repositorios;
using Microsoft.AspNetCore.Mvc;

namespace GerenciadorDeUsuarios.Controllers
{
    public class UsuarioController : Controller
    {
        public IUsuario Usuarios { get; }
        public UsuarioController(IUsuario usuarios)
        {
            this.Usuarios = usuarios;

        }
        public async Task<IActionResult> Todos(int totalPorPagina = 5, int pagina = 1)
        {

            var usuarios = await Usuarios.GetAll();
            
            var quantPaginas = Math.Ceiling(usuarios.Count/Convert.ToDouble(totalPorPagina));
            
            
            var usuariosPaginado = usuarios
                                        .Skip(totalPorPagina * (pagina - 1))
                                        .Take(totalPorPagina)
                                        .ToList();

            ViewData["PaginaAnterior"] = pagina > 1 ? pagina - 1 : 1;
            ViewData["ProximaPagina"] = pagina == quantPaginas ? pagina : pagina + 1;
            var viewModel = new UsuarioViewModel(usuariosPaginado,(int)quantPaginas);
            return View(viewModel);
        }

        private IActionResult NewMethod(System.Collections.Generic.List<Usuario> usuariosPaginado)
        {
            return View(usuariosPaginado);
        }

        public IActionResult Novo()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Novo([FromForm]Usuario usuario)
        {
            if(ModelState.IsValid)
            {
              await Usuarios.Save(usuario);
              return RedirectToAction("Todos");  
            }
           
            return View();      
                
            
        }


        public async Task<IActionResult> Editar(Guid id)
        {
            var usuario = await Usuarios.GetById(id);
            return View(usuario);
        }

        [HttpPost]
        [AutoValidateAntiforgeryToken]
        public async Task<IActionResult> Editar([FromForm]Usuario usuario, Guid id)
        {
            usuario.UsuarioId = id;
            await Usuarios.Update(usuario);
            return RedirectToAction("Todos");
        }

        public async Task<IActionResult> Deletar(Guid id)
        {
            var usuario = await Usuarios.GetById(id);
            return View(usuario);
        }

        [HttpPost, ActionName("Deletar")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> ConfirmacaoDeletar(Guid id)
        {
            
            await Usuarios.Delete(id);
            return RedirectToAction("Todos");
        }
        
       
        public IActionResult Permissoes(Guid id)
        {
            var usuario = Usuarios.GetUserWith(id);
            return View(usuario);
        } 


       
        

    }
}

Controllers/UsuariosController.cs
using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using GerenciadorDeUsuarios.Models;
using GerenciadorDeUsuarios.Repositorios;
using Microsoft.AspNetCore.Mvc;

namespace GerenciadorDeUsuarios.Controllers
{
    [Route("api/[controller]")]
    public class UsuariosController : Controller
    {
        public IUsuario Usuarios { get; }
        public UsuariosController(IUsuario usuarios)
        {
            this.Usuarios = usuarios;

        }
        public async Task<IList<Usuario>> Get()
        {
            return await Usuarios.GetAll();            
        }

        [HttpGet("{id}")]
        public async Task<Usuario> Get(Guid id)
        {
            return await Usuarios.GetById(id);
        }

        [HttpPost]
        public async Task Post([FromBody]Usuario usuario)
        {
            await Usuarios.Save(usuario);
        }

        [HttpPut("{id}")]
        public async Task Put([FromBody]Usuario usuario, Guid id)
        {
            usuario.UsuarioId = id;
            await Usuarios.Update(usuario);
        }
        [HttpDelete("{id}")]
        public async Task Delete(Guid id)
        {            
            await Usuarios.Delete(id);
        }
    }
}

Views/Shared/_Layout.cshtml
@{
    var nome = "Pedro";
}
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - GerenciadorDeUsuarios</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Usuario" asp-action="Todos" class="navbar-brand">GerenciadorDeUsuarios</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-controller="Usuario" asp-action="Todos">Usuario</a></li>
                    <li><a asp-controller="Permissao" asp-action="Todos">Permissões</a></li>
                    <!--<li><a asp-area="" asp-controller="Home" asp-action="About">About</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="Contact">Contact</a></li>-->
                    
                </ul>
            </div>
        </div>
    </nav>
    <div class="container body-content">
        <br>
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2017 - GerenciadorDeUsuarios</p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-K+ctZQ+LL8q6tP7I94W+qzQsfRV2a+AfHIi9k8z8l9ggpc8X+Ytst4yBo/hH+8Fk">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>

Views/Shared/_PermissaoForm.cshtml
@model Permissao

	<div class="row">
		<div class="col-md-4">
		</div>
		<div class="col-md-4">
			<form method="POST" >
                    @Html.AntiForgeryToken()
					 <div asp-validation-summary="All" class="text-danger"></div>
		     		<div class="form-group">
					<label asp-for="Nome">Nome</label>
					<input type="text" asp-for=Nome placeholder="Nome da Permissão" class="form-control" >
					<span asp-validation-for="Nome" class="text-danger"></span>
				</div>					
				<button type="submit" class="btn btn-default">
					Salvar
				</button>
			</form>
		</div>
		<div class="col-md-4">
		</div>
	</div>

Views/Shared/_UsuarioForm.cshtml
@model Usuario

	<div class="row">
		<div class="col-md-4">
		</div>
		<div class="col-md-4">
			<form method="POST" >
                    @Html.AntiForgeryToken()
					 <div asp-validation-summary="All" class="text-danger"></div>
		     		<div class="form-group">
					<label asp-for="Nome">Nome</label>
					<input type="text" asp-for=Nome placeholder="Nome do Usuario" class="form-control" >
					<span asp-validation-for="Nome" class="text-danger"></span>
				</div>
				<div class="form-group">
					<label asp-for="Email">Email</label>
					<input type="email" asp-for="Email" placeholder="Email do Usuario" class="form-control" >
					<span asp-validation-for="Email" class="text-danger"></span>
				</div>
				<div class="form-group">
					<label asp-for="Senha">Senha</label>
					<input type="password" asp-for="Senha" placeholder="Senha do Usuario" class="form-control" >
					<span asp-validation-for="Senha" class="text-danger"></span>
				</div>				
				<button type="submit" class="btn btn-default">
					Salvar
				</button>
			</form>
		</div>
		<div class="col-md-4">
		</div>
	</div>